// Frontend Mutations
export const SET_OPEN_SIDEBAR = "SET_OPEN_SIDEBAR"
export const SET_SHOW_SNACKBAR = "SET_SHOW_SNACKBAR"
export const SET_SHOW_DELETE_MODAL = "SET_SHOW_DELETE_MODAL"
export const SET_SHOW_SEARCH_MODAL = "SET_SHOW_SEARCH_MODAL"
export const SET_SHOW_BARCODE_MODAL = "SET_SHOW_BARCODE_MODAL"
export const SET_SHOW_BRAND_MODAL = "SET_SHOW_BRAND_MODAL"
export const SET_SHOW_CATEGORY_MODAL = "SET_SHOW_CATEGORY_MODAL"
export const SET_SHOW_SUPPLIER_MODAL = "SET_SHOW_SUPPLIER_MODAL"
export const SET_SHOW_CUSTOMER_MODAL = "SET_SHOW_CUSTOMER_MODAL"
export const SET_PRODUCT_VIEW_MODE = "SET_PRODUCT_VIEW_MODE"
export const SET_PAYMENT_TRAY = "SET_PAYMENT_TRAY"


// Cashier Mutations
export const ADD_ORDER = "ADD_ORDER"
export const UPDATE_ORDER = "UPDATE_ORDER"
export const REMOVE_ORDER = "REMOVE_ORDER"
export const CALCULATION = "CALCULATION"

//Product Mutations
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const SET_CURRENT = "SET_CURRENT"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const SET_SEARCH = "SET_SEARCH"


// Categories Mutations
export const SET_CATEGORIES = "SET_CATEGORIES"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"


// Brand Mutations
export const SET_BRANDS = "SET_BRANDS"
export const ADD_BRAND = "ADD_BRAND"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const DELETE_BRAND = "DELETE_BRAND"


// Supplier Mutations
export const SET_SUPPLIERS = "SET_SUPPLIERS"
export const DELETE_SUPPLIER = "DELETE_SUPPLIER"
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER"
export const ADD_SUPPLIER = "ADD_SUPPLIER"

// Customer Mutations
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER"
export const SET_CUSTOMERS = "SET_CUSTOMERS"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"

// Process Mutations
export const SET_CURRENT_DELETE = "SET_CURRENT_DELETE"
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT"
export const SET_CURRENT_SUPPLIER = "SET_CURRENT_SUPPLIER"

// Accounts Mutations
export const SET_ACCOUNTS = "SET_ACCOUNTS"
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT"
export const ADD_ACCOUNT = "ADD_ACCOUNT"
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
export const DELETE_ACCOUNT = "DELETE_ACCOUNT"

// Role Mutations
export const SET_ROLE = "SET_ROLE"
export const ADD_ROLE = "ADD_ROLE"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"


// Utility Mutations
export const SET_LOADING = "SET_LOADING"
